# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-20 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190515_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='名字')),
            ],
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='名字')),
                ('address', models.URLField(blank=True, max_length=128, null=True, verbose_name='地址')),
                ('email', models.EmailField(blank=True, max_length=128, null=True, verbose_name='邮箱')),
                ('date', models.DateField(verbose_name='时间')),
                ('cla', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Class')),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='specialty',
            field=models.CharField(max_length=32, null=True, verbose_name='专业'),
        ),
        migrations.AddField(
            model_name='number',
            name='num',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Userinfo', verbose_name='学号'),
        ),
        migrations.AddField(
            model_name='class',
            name='user',
            field=models.ManyToManyField(to='app.Userinfo'),
        ),
    ]
