# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-21 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_class_sch'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='cla_name',
            field=models.ManyToManyField(to='app.Class'),
        ),
    ]
