# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-21 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userinfo_cla_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='date',
            field=models.DateField(null=True, verbose_name='时间'),
        ),
    ]
