# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-27 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_disk_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, max_length=64, null=True, verbose_name='阿里云主机名')),
                ('ecsname', models.CharField(blank=True, max_length=64, null=True, verbose_name='阿里云实例ID')),
                ('login_port', models.CharField(blank=True, default='22', max_length=16, null=True, verbose_name='ssh登录端口')),
                ('cpu', models.CharField(blank=True, max_length=8, null=True, verbose_name='CPU')),
                ('mem', models.CharField(blank=True, max_length=8, null=True, verbose_name='内存/M')),
                ('speed', models.CharField(blank=True, default='5', max_length=8, null=True, verbose_name='带宽/M')),
                ('eth1_network', models.CharField(blank=True, max_length=32, null=True, verbose_name='公网IP')),
                ('eth0_network', models.CharField(max_length=32, verbose_name='私网IP')),
                ('sn', models.CharField(blank=True, max_length=64, null=True, verbose_name='sn')),
                ('kernel', models.CharField(blank=True, max_length=64, null=True, verbose_name='系统内核')),
                ('remarks', models.CharField(blank=True, max_length=2048, null=True, verbose_name='备注')),
                ('createtime', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建时间')),
                ('expirytime', models.CharField(blank=True, max_length=32, null=True, verbose_name='到期时间')),
                ('state', models.SmallIntegerField(blank=True, choices=[(1, 'Running'), (2, '下线'), (3, '关机'), (4, '删除')], null=True, verbose_name='主机状态')),
                ('disks', models.ManyToManyField(blank=True, null=True, to='app.Disk', verbose_name='磁盘')),
            ],
            options={
                'verbose_name_plural': '主机表',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_name', models.CharField(default='root', max_length=16, verbose_name='登录用户名')),
                ('login_pwd', models.CharField(blank=True, max_length=64, null=True, verbose_name='登录密码')),
                ('auth', models.CharField(blank=True, max_length=8, null=True, verbose_name='具有权限')),
            ],
            options={
                'verbose_name_plural': '主机用户表',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True, verbose_name='来源')),
            ],
            options={
                'verbose_name_plural': '主机来源表',
            },
        ),
        migrations.AddField(
            model_name='host',
            name='logining',
            field=models.ManyToManyField(blank=True, null=True, to='app.Login', verbose_name='授权用户'),
        ),
        migrations.AddField(
            model_name='host',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Region', verbose_name='所属区域'),
        ),
        migrations.AddField(
            model_name='host',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Source', verbose_name='来源类型'),
        ),
        migrations.AddField(
            model_name='host',
            name='the_upper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upper', to='app.Host', verbose_name='宿主机'),
        ),
    ]
