# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-27 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190527_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='region',
        ),
        migrations.RemoveField(
            model_name='host',
            name='the_upper',
        ),
        migrations.AlterField(
            model_name='host',
            name='disks',
            field=models.ManyToManyField(default=1, to='app.Disk', verbose_name='磁盘'),
        ),
        migrations.AlterField(
            model_name='host',
            name='ecsname',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='实例名'),
        ),
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='host',
            name='kernel',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='内核版本'),
        ),
        migrations.AlterField(
            model_name='host',
            name='login_port',
            field=models.CharField(blank=True, default='22', max_length=16, null=True, verbose_name='登录端口'),
        ),
        migrations.AlterField(
            model_name='host',
            name='logining',
            field=models.ManyToManyField(default=1, to='app.Login', verbose_name='所属用户'),
        ),
        migrations.AlterField(
            model_name='host',
            name='mem',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='内存'),
        ),
        migrations.AlterField(
            model_name='host',
            name='sn',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='SN'),
        ),
        migrations.AlterField(
            model_name='host',
            name='source',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Source', verbose_name='来源IP'),
        ),
        migrations.AlterField(
            model_name='host',
            name='speed',
            field=models.CharField(blank=True, default='5', max_length=8, null=True, verbose_name='带宽'),
        ),
        migrations.AlterField(
            model_name='host',
            name='state',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Running'), (2, '下线'), (3, '关机'), (4, '删除'), (5, '故障')], null=True, verbose_name='主机状态'),
        ),
    ]
