# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-27 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190527_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='region',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Region', verbose_name='地域'),
        ),
    ]
