# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-27 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_host_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='sch',
        ),
        migrations.RemoveField(
            model_name='class',
            name='user',
        ),
        migrations.RemoveField(
            model_name='host',
            name='disks',
        ),
        migrations.RemoveField(
            model_name='host',
            name='logining',
        ),
        migrations.RemoveField(
            model_name='host',
            name='region',
        ),
        migrations.RemoveField(
            model_name='host',
            name='source',
        ),
        migrations.RemoveField(
            model_name='number',
            name='num',
        ),
        migrations.RemoveField(
            model_name='school',
            name='cla',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='cla_name',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Disk',
        ),
        migrations.DeleteModel(
            name='Host',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Number',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.DeleteModel(
            name='Userinfo',
        ),
    ]
